In [4]:
## Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd

## load the dataset
data = gutenberg.raw('carroll-alice.txt')
## save to a file
with open('alice.txt', 'w') as file:
    file.write(data)


[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\Priyanshu\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [5]:
## Data Preprocessing

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

## load the dataset
with open('alice.txt', 'r') as file:
    text = file.read().lower()

## Tokenize the text-creating indexes for words
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index) + 1
total_words

2858

In [6]:
tokenizer.word_index

{'the': 1,
 "'": 2,
 'and': 3,
 'to': 4,
 'a': 5,
 'she': 6,
 'of': 7,
 'it': 8,
 'said': 9,
 'alice': 10,
 'in': 11,
 'was': 12,
 'you': 13,
 'i': 14,
 'that': 15,
 'as': 16,
 'her': 17,
 'at': 18,
 'on': 19,
 'with': 20,
 'all': 21,
 'had': 22,
 'be': 23,
 'for': 24,
 'so': 25,
 'very': 26,
 'not': 27,
 'but': 28,
 'this': 29,
 'little': 30,
 "'i": 31,
 'they': 32,
 'out': 33,
 'he': 34,
 'is': 35,
 'down': 36,
 'what': 37,
 'up': 38,
 'one': 39,
 'his': 40,
 'about': 41,
 'them': 42,
 'know': 43,
 'like': 44,
 'were': 45,
 'went': 46,
 'again': 47,
 'herself': 48,
 'then': 49,
 'would': 50,
 'no': 51,
 'could': 52,
 'have': 53,
 'if': 54,
 'thought': 55,
 'when': 56,
 'do': 57,
 'or': 58,
 'there': 59,
 'time': 60,
 'queen': 61,
 'into': 62,
 'see': 63,
 'me': 64,
 'off': 65,
 'king': 66,
 'did': 67,
 'your': 68,
 'by': 69,
 'began': 70,
 'its': 71,
 'turtle': 72,
 "'and": 73,
 'way': 74,
 'an': 75,
 'my': 76,
 'mock': 77,
 'quite': 78,
 'who': 79,
 "don't": 80,
 'hatter': 81,
 'gry

In [7]:
## create input sequences
input_sequences = []
for line in text.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i + 1]
        input_sequences.append(n_gram_sequence)

In [8]:
input_sequences

[[315, 490],
 [315, 490, 11],
 [315, 490, 11, 886],
 [315, 490, 11, 886, 69],
 [315, 490, 11, 886, 69, 1585],
 [315, 490, 11, 886, 69, 1585, 1586],
 [315, 490, 11, 886, 69, 1585, 1586, 1587],
 [316, 14],
 [316, 14, 36],
 [316, 14, 36, 1],
 [316, 14, 36, 1, 99],
 [316, 14, 36, 1, 99, 628],
 [10, 12],
 [10, 12, 268],
 [10, 12, 268, 4],
 [10, 12, 268, 4, 105],
 [10, 12, 268, 4, 105, 26],
 [10, 12, 268, 4, 105, 26, 491],
 [10, 12, 268, 4, 105, 26, 491, 7],
 [10, 12, 268, 4, 105, 26, 491, 7, 368],
 [10, 12, 268, 4, 105, 26, 491, 7, 368, 69],
 [10, 12, 268, 4, 105, 26, 491, 7, 368, 69, 17],
 [10, 12, 268, 4, 105, 26, 491, 7, 368, 69, 17, 441],
 [10, 12, 268, 4, 105, 26, 491, 7, 368, 69, 17, 441, 19],
 [10, 12, 268, 4, 105, 26, 491, 7, 368, 69, 17, 441, 19, 1],
 [887, 3],
 [887, 3, 7],
 [887, 3, 7, 369],
 [887, 3, 7, 369, 145],
 [887, 3, 7, 369, 145, 4],
 [887, 3, 7, 369, 145, 4, 57],
 [887, 3, 7, 369, 145, 4, 57, 137],
 [887, 3, 7, 369, 145, 4, 57, 137, 58],
 [887, 3, 7, 369, 145, 4, 57, 137

In [9]:
## Pad sequences
max_sequence_length = max([len(x) for x in input_sequences])
max_sequence_length

18

In [10]:
input_sequences=np.array(pad_sequences(input_sequences, maxlen=max_sequence_length, padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,  315,  490],
       [   0,    0,    0, ...,  315,  490,   11],
       [   0,    0,    0, ...,  490,   11,  886],
       ...,
       [   0,    0,    0, ...,    3,    1, 2857],
       [   0,    0,    0, ...,    1, 2857, 1563],
       [   0,    0,    0, ..., 2857, 1563,  846]], dtype=int32)

In [11]:
## create predictors and label
import tensorflow as tf
x, y = input_sequences[:, :-1], input_sequences[:, -1]

In [12]:
x

array([[   0,    0,    0, ...,    0,    0,  315],
       [   0,    0,    0, ...,    0,  315,  490],
       [   0,    0,    0, ...,  315,  490,   11],
       ...,
       [   0,    0,    0, ...,  328,    3,    1],
       [   0,    0,    0, ...,    3,    1, 2857],
       [   0,    0,    0, ...,    1, 2857, 1563]], dtype=int32)

In [13]:
y

array([ 490,   11,  886, ..., 2857, 1563,  846], dtype=int32)

In [14]:
y=tf.keras.utils.to_categorical(y, num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
## Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [16]:
#Train our LSTM RNN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, GRU

## Define the model
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_length-1))
model.add(LSTM(150, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words, activation='softmax'))

## Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.build(input_shape=(None, max_sequence_length))
model.summary()

c:\Users\Priyanshu\coding\python_projects\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 18, 100)        │       285,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 18, 150)        │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 18, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │       100,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 2858)           │       288,658 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 825,458 (3.15 MB)

 Trainable params: 825,458 (3.15 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
## Define early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

In [ ]:
#Train our GRU RNN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, GRU

## GRU RNN
## Define the model
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_length-1))
model.add(GRU(150, return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(100))
model.add(Dense(total_words, activation='softmax'))

## Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.build(input_shape=(None, max_sequence_length))
model.summary()

c:\Users\Priyanshu\coding\python_projects\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 14, 100)        │       481,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 14, 150)        │       113,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 14, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ (None, 100)            │        75,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4818)           │       486,618 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,157,418 (4.42 MB)

 Trainable params: 1,157,418 (4.42 MB)

 Non-trainable params: 0 (0.00 B)

In [19]:
## Train the model
history = model.fit(x_train, y_train, epochs=100,validation_data=(x_test, y_test),verbose=1)


Epoch 1/100
634/634 ━━━━━━━━━━━━━━━━━━━━ 16s 25ms/step - accuracy: 0.7130 - loss: 1.1219 - val_accuracy: 0.1261 - val_loss: 10.8873
Epoch 2/100
634/634 ━━━━━━━━━━━━━━━━━━━━ 17s 26ms/step - accuracy: 0.7149 - loss: 1.1149 - val_accuracy: 0.1275 - val_loss: 10.9516
Epoch 3/100
634/634 ━━━━━━━━━━━━━━━━━━━━ 17s 27ms/step - accuracy: 0.7210 - loss: 1.0963 - val_accuracy: 0.1279 - val_loss: 10.9699
Epoch 4/100
634/634 ━━━━━━━━━━━━━━━━━━━━ 18s 28ms/step - accuracy: 0.7184 - loss: 1.0928 - val_accuracy: 0.1303 - val_loss: 11.0044
Epoch 5/100
634/634 ━━━━━━━━━━━━━━━━━━━━ 17s 27ms/step - accuracy: 0.7219 - loss: 1.0821 - val_accuracy: 0.1289 - val_loss: 11.0838
Epoch 6/100
634/634 ━━━━━━━━━━━━━━━━━━━━ 17s 27ms/step - accuracy: 0.7228 - loss: 1.0757 - val_accuracy: 0.1299 - val_loss: 11.0679
Epoch 7/100
634/634 ━━━━━━━━━━━━━━━━━━━━ 17s 27ms/step - accuracy: 0.7297 - loss: 1.0641 - val_accuracy: 0.1279 - val_loss: 11.1239
Epoch 8/100
634/634 ━━━━━━━━━━━━━━━━━━━━ 17s 27ms/step - accuracy: 0.7334 - 

In [20]:
##function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_length):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_length:
        token_list = token_list[-(max_sequence_length-1):]
    token_list = pad_sequences([token_list], maxlen=max_sequence_length-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None    

In [21]:
input_text = "ALL PERSONS MORE THAN A MILE HIGH TO LEAVE THE"
print(f"Input text: {input_text}")
max_sequence_length= model.input_shape[1]+1
next_word = predict_next_word(model, tokenizer, input_text, max_sequence_length)
print(f"Next word prediction: {next_word}")

Input text: ALL PERSONS MORE THAN A MILE HIGH TO LEAVE THE
Next word prediction: court


In [22]:
##Save the model
model.save('Next_word_lstm.h5')
##Save the tokenizer
import pickle
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)